//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamMaker()
        {
            this.ExamWriter = new HashSet<ExamWriter>();
        }
    
        public int examMakerid { get; set; }
        public int examNo { get; set; }
        public string examName { get; set; }
        public Nullable<int> examLocationid { get; set; }
        public Nullable<int> supervisorid { get; set; }
        public Nullable<int> questionMakerid { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> lessonid { get; set; }
    
        public virtual ExamLocation ExamLocation { get; set; }
        public virtual Group Group { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual QuestionMaker QuestionMaker { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamWriter> ExamWriter { get; set; }
    }
}
