//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionMaker()
        {
            this.ExamMaker = new HashSet<ExamMaker>();
        }
    
        public int questionMakerid { get; set; }
        public string question { get; set; }
        public Nullable<int> subjectid { get; set; }
        public Nullable<int> questionTypeid { get; set; }
        public Nullable<int> degreeOfDifficultid { get; set; }
        public Nullable<int> questionScore { get; set; }
        public Nullable<int> answersid { get; set; }
        public Nullable<int> mChoiceOptionid { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual DegreeOfDifficult DegreeOfDifficult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMaker> ExamMaker { get; set; }
        public virtual MChoiceOption MChoiceOption { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
