//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaker.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_examWriter
    {
        public string question { get; set; }
        public int examNo { get; set; }
        public string groupNo { get; set; }
        public string answers { get; set; }
        public string studentAnswer { get; set; }
        public string result { get; set; }
    }
}
